---
- name: Verificar que los usuarios fueron creados
  hosts: servidores
  become: true
  gather_facts: yes

  tasks:
    - name: Verificar si el usuario carlos existe
      ansible.builtin.command: id carlos
      register: carlos_user
      ignore_errors: true

    - name: Carlos fue creado
      ansible.builtin.debug:
        msg: "El usuario carlos existe"
      when: carlos_user.rc == 0

    - name: Verificar si el usuario marta existe
      ansible.builtin.command: id marta
      register: marta_user
      ignore_errors: true

    - name: Marta fue creada
      ansible.builtin.debug:
        msg: "El usuario marta existe"
      when: marta_user.rc == 0

